### ISSUE TITLE
bug: panic on start if monitoring.sentryDSN is unset

### ISSUE THREAD

**Issue by jbergstroem** [ihippik/wal-listener#33]
Mostly from example config, removing the monitoring bits:
```
listener:
  slotName: cs2
  refreshConnection: 30s
  heartbeatInterval: 10s
  filter:
    tables:
      campaigns:
        - insert
        - update
  topicsMap:
    schema_table_name: "notifier"
logger:
  level: info
  fmt: json
database:
  host: postgres
  port: 5432
  name: cs2
  user: cs2
  password: cs2
  debug: false
publisher:
  type: nats
  address: nats:4222
  topic: "wal_listener"
  topicPrefix: "wal"
```

..when started:
```
wal-listener-1  | panic: runtime error: invalid memory address or nil pointer dereference
wal-listener-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9a74f4]
wal-listener-1  |
wal-listener-1  | goroutine 1 [running]:
wal-listener-1  | main.main.func1(0x4000652dc0)
wal-listener-1  |       /listener/cmd/wal-listener/main.go:47 +0x134
wal-listener-1  | github.com/urfave/cli/v2.(*Command).Run(0x40006c0580, 0x4000652dc0, {0x4000130040, 0x1, 0x1})
wal-listener-1  |       /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/command.go:277 +0x71c
wal-listener-1  | github.com/urfave/cli/v2.(*App).RunContext(0x4000654000, {0xdeebd0, 0x16160e0}, {0x4000130040, 0x1, 0x1})
wal-listener-1  |       /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/app.go:335 +0x514
wal-listener-1  | github.com/urfave/cli/v2.(*App).Run(...)
wal-listener-1  |       /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/app.go:309
wal-listener-1  | main.main()
wal-listener-1  |       /listener/cmd/wal-listener/main.go:89 +0x2cc
wal-listener-1 exited with code 2
```

**Comment by ihippik** [comment]
oh, my bad - will fix it soon, thank you!

**Comment by ihippik** [comment]
fixed
